### ISSUE TITLE
这个如何实现路由选择？将不同类协议的数据发送到不同线路

### ISSUE THREAD

**Issue by netscrt** [crabkun/Switcher#1]

**Comment by crabkun** [comment]
利用正则来匹配的，在core目录的core.go文件，GetAddrByRegExp函数

**Comment by netscrt** [comment]
您可能没理解我的意思，我是说 有没有可能在您这个代码的基础上将它改造成基于应用层协议的路由软件？
这样我们可以基于应用层协议分类，在多条廉价线路上跑 优先级低的数据，例如BT数据，优先级高的数据跑在线路质量好，价格高的线路上！这样可以更合理的利用资源

**Comment by crabkun** [comment]
首先您说的这个要写出来，得针对某一个协议进行解析。这个代码只是简单用正则进行匹配，没法改成您说的那样，所以还不如直接重新写了。
