### ISSUE TITLE
regexp可以增加一个回落吗？

### ISSUE THREAD

**Issue by AKEBI-NUKUI** [crabkun/Switcher#14]
大佬好，这个程序很牛逼，帮我解决了一个端口使用gost分流同一host无法嗅探https或http的问题，感谢大佬！！
不过regexp可以增加一个回落吗？就是如果检测到不符合所有的regexp正则就回落到某个地址。这样子的话可能会有种探测防御的感觉？

**Comment by AKEBI-NUKUI** [comment]
噢 似乎直接添加多一个无regexp的address就能做回落了
感谢大佬！！！！

**Comment by crabkun** [comment]
嗯，是可以这样进行兜底的

**Comment by AKEBI-NUKUI** [comment]
大佬！！
跪求把 -c 或者--config位置参数加上！！！

**Comment by crabkun** [comment]
好的，今晚加上。

**Comment by AKEBI-NUKUI** [comment]
> 好的，今晚加上。

感谢大佬！！！！！！

**Comment by crabkun** [comment]
你好，已加上。

**Comment by AKEBI-NUKUI** [comment]
感谢大佬！！！！！！
