### ISSUE TITLE
这是开启一个新端口复用，我只能访问到对方的80端口，在80端口上面复用rdp的话，应该怎么弄？

### ISSUE THREAD

**Issue by wpf97** [crabkun/Switcher#3]

**Comment by crabkun** [comment]
在对方电脑上把原先80端口改成81，然后开复用工具跑在80端口，在配置文件里面把HTTP请求转发到81端口，RDP请求转发到3389端口

**Comment by CCCougar** [comment]
很棒的项目！但我也遇到 @wpf97 一样的问题，期望能在不改变原来80端口服务的情况下，复用80端口，效果类似下图：
![image](https://github.com/crabkun/switcher/assets/44094753/bc65eebd-0a56-42b4-beda-0ffc21cd91b0)
但在学习了另一个项目[sslh](https://github.com/yrutschle/sslh)后发现可以通过修改80端口服务监听端口由0.0.0.0:80->127.0.0.1:80达到复用80端口效果：
![image](https://github.com/crabkun/switcher/assets/44094753/4ec4d503-0b9e-4284-88e1-fbea60441cb3)
这样虽然看着是复用了80，但还是得修改80端口的服务，感觉挺鸡肋的
