### ISSUE TITLE
用Windows 自带的远程桌面软件不能连接成功， Mac下的RemoteDesktop能够连接成功

### ISSUE THREAD

**Issue by SunRise-nc** [crabkun/Switcher#5]
Mac下的Microsoft Remote Desktop 能够远程桌面， 但是用Windows10下的远程桌面就不能连接成功。

**Comment by crabkun** [comment]
你好，可以试下把^\x03\x00\x00\x13改成^\x03\x00\x00

**Comment by SunRise-nc** [comment]
yes,  u r right. thks!
