### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by pizixi** [crabkun/Switcher#6]
好用，个人小建议，如果能加上ip 白名单就更好了，正则表达式里面的rdp 或者ssh协议能配置ip白名单，就更安全了。

**Comment by crabkun** [comment]
你好，感谢支持。
是每个target不同IP白名单，还是每个rule不同白名单？

**Comment by pizixi** [comment]
![image](https://user-images.githubusercontent.com/56673215/116225865-e71ea900-a784-11eb-8ac5-3c9368acf3b2.png)
这里配置是不是更灵活

**Comment by pizixi** [comment]
![image](https://user-images.githubusercontent.com/56673215/117970112-e0825b00-b35a-11eb-8fa7-3d1f70f9ffdb.png)
天天被这肉鸡攻击，要是有黑白名单就好了，发现有异常攻击，就可以直接拉黑他的ip

**Comment by crabkun** [comment]
你好，最近在外面出差，等回来就弄上

**Comment by crabkun** [comment]
你好，已加上。目前黑名单IP在rules层。感觉放到targets层如果有很多target都要配置同一个IP的话还挺麻烦的。你先试试是否满足要求，如果不满足的话我再新开一个分支帮你修改吧。
