### ISSUE TITLE
Missing project dependency file [go.sum]

### ISSUE THREAD

**Issue by 6769** [crabkun/Switcher#7]
建议增加git对`go.sum` 文件的追踪，毕竟编译和版本锁定需要两个文件一起支持，go.mod和go.sum，
像知名项目[logrus](https://github.com/Sirupsen/logrus)都是把sum文件加入了的，
![image](https://user-images.githubusercontent.com/7290836/119294521-3cb47b80-bc87-11eb-9430-924f4817efe5.png)

不然编译时还要修复一下sum文件
![image](https://user-images.githubusercontent.com/7290836/119294555-4c33c480-bc87-11eb-9f32-e7c33860870c.png)

**Comment by crabkun** [comment]
你好，已经补上，感谢支持~~
