### ISSUE TITLE
对go新用户缺乏友好性

### ISSUE THREAD

**Issue by ThomasSun001** [crabkun/Switcher#9]
config.go:6:2: cannot find package "github.com/sirupsen/logrus" in any of:
        /usr/lib/go-1.10/src/github.com/sirupsen/logrus (from $GOROOT)
        /home/ubuntu/go/src/github.com/sirupsen/logrus (from $GOPATH)

**Comment by crabkun** [comment]
你好，项目是支持go mod依赖管理的的，或许你看的资料是老版本的GOPATH方式。
非常简单的编译方法：
1、确保你的go版本是1.13以上，建议去官网下载最新
2、将本项目clone到GOPATH以外的目录，不要放到GOPATH里面
然后打开命令行在此目录执行
1、go env -w GOPROXY=https://goproxy.cn,direct
2、go mod download
3、go build .
第一步的目的是为了使用国内的gomod仓库，如果你的网络能直接访问国外网站可以不用执行此步骤
执行完以上命令之后目录下面就生成好可执行文件了
有疑问可以继续留言

**Comment by omaidb** [comment]
执行第2步的时候
提示：go: no modules specified (see 'go help mod download')
![image](https://github.com/crabkun/switcher/assets/18365223/a689d48b-da6e-455b-915c-f785dd1d2535)

**Comment by omaidb** [comment]
重新拉了一边代码，可以了
